version: "3.9"

services:
  db:
    image: postgres:14.5-bullseye
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tiery

    ports:
      - "5432:5432"

    volumes:
      - db:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - mode: host
        protocol: tcp
        published: "${MINIO_PORT:-9002}"
        target: 9002
      - mode: host
        protocol: tcp
        published: "${MINIO_CONSOLE_PORT:-9003}"
        target: 9003
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniominio
    command: server --address :"${MINIO_PORT:-9002}" --console-address :"${MINIO_CONSOLE_PORT:-9003}" /data

volumes:
  db:
  minio_storage:
